### ISSUE TITLE
Failed to run `launchable record build` with Jenkins GitHub Branch Source build on Launchable CLI 1.66.1

### ISSUE THREAD

**Issue by basil** [launchableinc/cli#581]
After upgrading the Launchable CLI all of our PR builds started failing like [this](https://ci.jenkins.io/job/Core/job/jenkins/job/PR-8267/1/console):

```
10:18:03  + launchable record build --name jenkins-Core-jenkins-PR-8267-1 --source jenkinsci/jenkins=.
10:18:04  Launchable recorded 1 commit from repository /home/jenkins/agent/workspace/Core_jenkins_PR-8267
10:18:04  Can't get commit hash. Do you run command under git-controlled directory? If not, please set a directory use by --source option.
10:18:04  'GIT_LOCAL_BRANCH'
```

Last working version was 1.66.0.

**Comment by basil** [comment]
#570 appears to be the cause of the issue. This PR assumes that the `GIT_BRANCH` and/or `GIT_LOCAL_BRANCH` are set, but they are not set on my Jenkins controller. The following environment variables are set:

```
BRANCH_NAME=PR-8266
CHANGE_AUTHOR=dependabot[bot]
CHANGE_BRANCH=dependabot/maven/org.jvnet.hudson-commons-jelly-tags-define-1.1-jenkins-20230713
CHANGE_ID=8266
CHANGE_TARGET=master
CHANGE_TITLE=Bump commons-jelly-tags-define from 1.1-jenkins-20230124 to 1.1-jenkins-20230713
CHANGE_URL=https://github.com/jenkinsci/jenkins/pull/8266
```

**Comment by basil** [comment]
Rolled back in https://github.com/jenkins-infra/packer-images/pull/745.

**Comment by basil** [comment]
Official documentation is here: https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.properties

**Comment by basil** [comment]
I just tested locally on my development Jenkins controller and found that these environment variables are set only when cloning a repository with the Git plugin directly:

```
GIT_PREVIOUS_SUCCESSFUL_COMMIT=6d66a8acdae76e62556c6cc2f3011b5eb031c94f
GIT_COMMIT=6d66a8acdae76e62556c6cc2f3011b5eb031c94f
GIT_BRANCH=origin/master
GIT_URL=https://github.com/basil/simple-maven-project-with-tests.git
GIT_PREVIOUS_COMMIT=6d66a8acdae76e62556c6cc2f3011b5eb031c94f
```

Most Jenkins users whose code is on GItHub, including our production use case on ci.jenkins.io, are instead using the Pipeline: Multibranch and GitHub Branch Source Plugin rather than the Git plugin. In this style of usage, the environment variables are different (as documented in https://github.com/jenkinsci/branch-api-plugin/blob/master/src/main/resources/jenkins/branch/BranchNameContributor/buildEnv.properties). So I would recommend checking environment variables in the following order:

- `CHANGE_BRANCH` (for PR Multibranch plugin builds)
- `CHANGE_TARGET` (for PR Multibranch plugin builds)
- `BRANCH_NAME` (for non-PR Multibranch plugin builds)
- `GIT_BRANCH` (for GIt plugin builds)
- `GIT_LOCAL_BRANCH` (for Git plugin builds)

**Comment by kohsuke** [comment]
My apologies for this mishap. We released v1.67.3 to roll back the problematic change.

**Comment by basil** [comment]
Thank you for the quick response!

**Comment by basil** [comment]
Still broken as of 1.75.0: https://github.com/jenkins-infra/helpdesk/issues/3756

**Comment by basil** [comment]
Reverted to 1.66.0 (for the second time). Can this ticket be reopened?
